import { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import router from 'next/router';

import { CharacterCard, Episode } from '@/components/index';
import { styled } from '@/stitches';
import { getEpisodes, getSingleCharacter } from 'lib/requests';
import { transformCharacterEpisodes } from 'lib/helpers';
import { Character, Episode as EpisodeType } from '@/types';

interface SingleCharacterPageProps {
  episodes: Array<EpisodeType>;
  character: Character;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query;
  let character = {};
  let episodes: any[] = [];

  try {
    const response = await getSingleCharacter(id as string);

    if (response?.id) {
      episodes = await getEpisodes(response.episode as string[]);
    }

    character = response;
  } catch (error) {}

  return {
    props: {
      character,
      episodes: transformCharacterEpisodes(episodes) as Array<EpisodeType>,
    },
  };
};

const SingleCharacterPage: NextPage<SingleCharacterPageProps> = ({ character, episodes }) => {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="header flex">
          <button onClick={() => router.back()}>All Characters</button>
          <h2 className="title">Character</h2>
        </div>
        <div className="grid">
          <div className="character">
            <CharacterCard
              {...character}
              status={character.status.toLocaleLowerCase() as 'alive' | 'dead' | 'unknown'}
            />
          </div>

          <div className="content">
            <h3>Episodes</h3>
            <div className="content-grid">
              {episodes.map((e: EpisodeType) => (
                <Episode key={e.id} {...e} />
              ))}
            </div>
          </div>
        </div>
      </Container>
    </>
  );
};

const Container = styled('div', {
  maxWidth: '1280px',
  margin: '0 auto',
  position: 'relative',

  '.grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: 10,
    marginBottom: 50,
  },

  '.header': {
    padding: '20px 0',
    alignItems: 'center',
    justifyContent: 'space-between',

    button: {
      color: '$blue',
      backgroundColor: 'white',
      border: 0,
      cursor: 'pointer',
    },
  },

  '.character': {
    gridColumn: 'span 4',
  },

  '.image-container': {
    height: 450,
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
  },

  '.content': {
    gridColumn: 'span 8',
    '.content-grid': {
      marginTop: 20,
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
    },
  },
});

export default SingleCharacterPage;
