import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import router from 'next/router';

import { Header, Filters, CharacterCard } from '@/components/index';
import { styled } from '@/stitches';
import { Character, RequestInfo, FilterType } from '@/types';
import { getCharacters } from 'lib/requests';

const transformCharacters = (data: Character[]) => {
  return data.map(({ name, status, species, location, gender, id, image }: Character): Character => {
    return {
      name,
      status: status.toLocaleLowerCase(),
      species,
      location,
      gender,
      id,
      image,
    };
  });
};

const isEmpty = (value: Array<any>) => value.length === 0;

interface HomePageProps {
  requestInfo: RequestInfo;
  characters: Array<Character>;
}

export async function getServerSideProps() {
  let requestInfo = {};
  let characters = {};

  try {
    const response = await getCharacters({
      status: '',
      gender: '',
      species: '',
      pageNumber: 1,
    });

    requestInfo = response.info;
    characters = transformCharacters(response.results);
  } catch (error) {}

  return {
    props: {
      requestInfo,
      characters,
    },
  };
}

interface Filters {
  status: string;
  gender: string;
  species: string;
}

const initialFilters = {
  status: '',
  gender: '',
  species: '',
};

const Home: NextPage<HomePageProps> = ({ characters: propInCharacters = [], requestInfo: propInRequestInfo = {} }) => {
  let [characters, setCharacters] = useState<Character[]>(propInCharacters);
  let [pageNumber, setPageNumber] = useState(1);
  let [requestInfo, setInfo] = useState<RequestInfo>(propInRequestInfo);

  const [filters, setFilters] = useState<Filters>(initialFilters);

  if (isEmpty(propInCharacters)) {
    return <NoCharacters />;
  }

  async function getfilteredCharacters(args: Filters) {
    const { results } = await getCharacters(args);

    if (results) {
      setCharacters(transformCharacters(results));
      return;
    }

    setCharacters([]);
  }

  function onFilterChange(type: FilterType, value: string) {
    const newFilters = {
      ...filters,
      [type]: value,
    };
    setFilters(newFilters);

    getfilteredCharacters(newFilters);
  }

  function onFilterClear() {
    setFilters(initialFilters);
    setCharacters(propInCharacters);
  }

  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Header title="All Characters" />
        <div className="grid">
          <div className="filters">
            <Filters onClear={onFilterClear} onFilterChange={onFilterChange} />
          </div>

          <div className="content">
            {isEmpty(characters) ? (
              <EmptyFilters />
            ) : (
              <>
                {characters.map((character: Character) => (
                  <CharacterCard {...character} key={character.id} />
                ))}
              </>
            )}
          </div>
        </div>
      </MainLayout>
    </div>
  );
};

const NoCharacters = () => {
  return (
    <NoCharactersContainer className="flex">
      <p>Hey, We {"couldn't"} find any rick and morty characters</p>
      <button onClick={() => router.reload()}>Reload page</button>
    </NoCharactersContainer>
  );
};

const EmptyFilters = () => {
  return (
    <div className="empty-filter-results flex">
      <p>Sorry, we are unable to find any characters for this filter</p>
    </div>
  );
};

const NoCharactersContainer = styled('div', {
  justifyContent: 'center',
  alignItems: 'center',
  outline: '1px dotted red',
  height: '100vh',
  flexDirection: 'column',

  button: {
    border: '0px',
    backgroundColor: '$blue',
    marginTop: 10,
    height: 46,
    padding: '0 25px',
    color: '$loContrast',
    borderRadius: 4,
    cursor: 'pointer',
  },
});

const MainLayout = styled('section', {
  fontFamily: '$system',
  maxWidth: '1280px',
  margin: '0 auto',

  '*': {
    outline: '1px dotted red',
  },

  '.empty-filter-results': {
    width: '100%',
    gridColumn: 'span 8',
    justifyContent: 'center',
    alignItems: 'center',
  },

  '.grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: 10,

    '.filters': {
      gridColumn: 'span 3',
    },

    '.content': {
      gridColumn: 'span 9',
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      justifyContent: 'space-between',
      gap: 20,
    },
  },
});

export default Home;
