import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { Header, Filters, CharacterCard } from '@/components/index';
import { styled } from '@/stitches';
import { Character, RequestInfo } from '@/types';
import { getCharacters } from 'lib/requests';

const testCharacter: Character = {
  created: '2017-11-04T18:48:46.250Z',
  episode: ['https://rickandmortyapi.com/api/episode/1', 'https://rickandmortyapi.com/api/episode/2'],
  gender: 'Male',
  id: 1,
  image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
  location: {
    name: 'Citadel of Ricks',
    url: 'https://rickandmortyapi.com/api/location/3',
  },
  name: 'Rick Sanchez',
  origin: {
    name: 'Earth (C-137)',
    url: 'https://rickandmortyapi.com/api/location/1',
    type: '',
    created: '',
    id: '',
    dimension: '',
  },
  species: 'Human',
  status: 'Alive',
  type: '',
  url: 'https://rickandmortyapi.com/api/character/1',
  residents: [],
};

const transforCharacters = (data: Array<Character>) => {
  return data.map(({ name, status, species, location, gender, id, image }: Character) => {
    return {
      name,
      status,
      species,
      location,
      gender,
      id,
      image,
    };
  });
};

interface HomePageProps {
  requestInfo: RequestInfo;
  characters: Array<Character>;
}

export async function getServerSideProps() {
  let requestInfo = {};
  let characters = {};

  try {
    const response = await getCharacters({
      status: '',
      gender: '',
      species: '',
      pageNumber: 1,
    });

    requestInfo = response.info;
    characters = transforCharacters(response.results);
  } catch (error) {}

  console.log('response', { requestInfo });

  return {
    props: {
      requestInfo,
      characters,
    },
  };
}

const Home: NextPage<HomePageProps> = ({ characters: propInCharacters = [], requestInfo: propInRequestInfo = {} }) => {
  let [characters, setCharacters] = useState<Character[]>(propInCharacters);
  let [pageNumber, setPageNumber] = useState(1);
  // let [status, setStatus] = useState('');
  // let [gender, setGender] = useState('');
  // let [species, setSpecies] = useState('');
  let [requestInfo, setInfo] = useState<RequestInfo>();

  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Header title="All Characters" />
        <div className="grid">
          <div className="filters">
            <Filters onClear={() => {}} onFilterChange={() => {}} />
          </div>

          <div className="content">
            {characters.map((character: Character) => (
              <CharacterCard {...character} key={character.id} />
            ))}
          </div>
        </div>
      </MainLayout>
    </div>
  );
};

const MainLayout = styled('section', {
  fontFamily: '$system',
  maxWidth: '1280px',
  margin: '0 auto',

  '*': {
    outline: '1px dotted red',
  },

  '.grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: 10,

    '.filters': {
      gridColumn: 'span 3',
    },

    '.content': {
      gridColumn: 'span 9',
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      justifyContent: 'space-between',
      gap: 20,
    },
  },
});

export default Home;
